import Head from "next/head";
import styles from "../styles/Home.module.scss";
import Header from "../components/header";
import Main from "../components/main";
import InfoContainer from "../components/infoContainer";
import Footer from "../components/footer";
export default function Home() {
    return (
        <div className={styles.main_container}>
            <Head>
                <title>Frontend Mentor | Skilled e-learning landing page</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="./images/favicon-32x32.png" />
            </Head>
            <Header />
            <Main />
            <InfoContainer />
            <Footer />
        </div>
    );
}
